#!/usr/bin/env bash
# This script installs and configures Nginx on a web server
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx restart
if curl -s http://localhost | grep -q "Hello World!"; then
    echo "Nginx installed and configured successfully!"
else
i    echo "Error: Nginx configuration or installation failed."
fi
