#!/bin/bash
# Configure Nginx to have a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '/server_name _;/a\    error_page 404 /404.html;\n' /etc/nginx/sites-available/default
sudo service nginx restart

