#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string

#Update packages
sudo apt-get update
sudo apt-get install -y nginx

# code to redirect a specific endpoint (eg: redirect /redirect_me to https://www.dhokabeatz.com)
echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.twitter.com\/dhokabeatz_ permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#custome HTTP header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#test configuration file
sudo nginx -t

#restart the server
sudo service nginx restart


