#!/usr/bin/env bash
# Configure ufw to block all incoming traffic except specified ports

# Reset ufw to default settings
sudo ufw --force reset

# Block all incoming traffic
sudo ufw default deny incoming

# Allow incoming SSH, HTTP, and HTTPS traffic
sudo ufw allow 22/tcp  # SSH
sudo ufw allow 80/tcp  # HTTP
sudo ufw allow 443/tcp # HTTPS

# Enable ufw
sudo ufw --force enable

