#!/usr/bin/env bash
# This script configures Nginx to run as nginx user and listen on port 8080

# Backup original Nginx configuration file
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

# Update Nginx configuration
sed -i 's/user nginx;/user nginx;\n    listen 8080;/g' /etc/nginx/nginx.conf

# Restart Nginx
service nginx restart

