#!/usr/bin/env bash
# This script connects to the server using the private key ~/.ssh/school and user ubuntu

# SSH connection command using the private key
ssh -i ~/.ssh/school ubuntu@54.160.117.237
