#!/usr/bin/env bash
# This script connects to the server using the private key ~/.ssh/school and user ubuntu

# Server IP address or hostname
server_ip=54.160.117.237

# SSH connection command using the private key
ssh -i ~/.ssh/school ubuntu@"$server_ip"

